#!/bin/tcsh
# #1 is the source code file, minus the '.c'

mpicc -Wall -pg -c $argv[1].c
mpicc -Wall -pg -c CVclistaLib.c
mpicc -o $argv[1] -pg -I /usr/local/atlas-3.9.23/include/ -L /usr/local/atlas-3.9.23/lib/ -latlas -lcblas $argv[1].o CVclistaLib.o
